# Generated by Django 4.2.1 on 2023-05-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prompt', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='react',
            name='departement',
        ),
        migrations.AddField(
            model_name='react',
            name='department',
            field=models.CharField(default='default_department', max_length=100),
        ),
        migrations.AlterField(
            model_name='react',
            name='employee',
            field=models.CharField(max_length=100),
        ),
    ]
